# Generated by Django 2.2.4 on 2020-07-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_student',
            name='Nationality',
            field=models.CharField(choices=[('Other', 'Other'), ('Pakistani', 'Pakistani')], max_length=120),
        ),
        migrations.AlterField(
            model_name='add_student',
            name='grade',
            field=models.CharField(choices=[('C', 'C'), ('Fail', 'Fail'), ('B', 'B'), ('A', 'A')], max_length=120),
        ),
        migrations.AlterField(
            model_name='add_teacher',
            name='experience',
            field=models.CharField(choices=[('3 Year', '3 Year'), ('1 Year', '1 Year'), ('2 Year', '2 Year'), ('4 Year', '4 Year')], max_length=50),
        ),
        migrations.AlterField(
            model_name='add_teacher',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=120),
        ),
    ]
