# Generated by Django 2.2.4 on 2020-07-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20200715_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_student',
            name='Nationality',
            field=models.CharField(choices=[('Pakistani', 'Pakistani'), ('Other', 'Other')], max_length=120),
        ),
        migrations.AlterField(
            model_name='add_student',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='add_student',
            name='domicile',
            field=models.CharField(choices=[('Charsadda', 'Charsadda'), ('Peshawar', 'Peshawar'), ('FATA', 'FATA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='add_student',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='add_student',
            name='exam_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='add_student',
            name='father_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='add_student',
            name='father_ocupation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='add_student',
            name='grade',
            field=models.CharField(choices=[('Fail', 'Fail'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=120),
        ),
        migrations.AlterField(
            model_name='add_student',
            name='institute_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='add_student',
            name='student_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='add_teacher',
            name='experience',
            field=models.CharField(choices=[('4 Year', '4 Year'), ('1 Year', '1 Year'), ('3 Year', '3 Year'), ('2 Year', '2 Year')], max_length=50),
        ),
        migrations.AlterField(
            model_name='add_teacher',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Male', 'Male'), ('Female', 'Female')], max_length=120),
        ),
    ]
